#!/usr/bin/env bash
# install-windows.sh — bootstrap cursor-std on Windows (Git Bash / MSYS).
#
# Usage (in Git Bash — not PowerShell / CMD / System32 bash.exe):
#   cd /d/project/cursor-standards
#   ./install-windows.sh
#
# Why a separate script: on Git Bash / MSYS, `ln -s` often copies the file
# instead of creating a real symlink. A copied bin/cursor-std then resolves
# lib/ relative to ~/.local and fails. This script always writes a tiny
# wrapper that exec's the real checkout, which works reliably on Windows.
#
# macOS / Linux: use ./install.sh instead.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$REPO_ROOT/bin/cursor-std"
[ -f "$SRC" ] || { echo "error: $SRC not found" >&2; exit 1; }
chmod +x "$SRC" 2>/dev/null || true

BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$BIN_DIR"
DEST="$BIN_DIR/cursor-std"

rm -f "$DEST"
cat > "$DEST" <<EOF
#!/usr/bin/env bash
# Auto-generated by cursor-standards/install-windows.sh — do not edit.
exec "$SRC" "\$@"
EOF
chmod +x "$DEST" 2>/dev/null || true

echo "Installed cursor-std wrapper -> $DEST"
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;
  *) echo "note: $BIN_DIR is not on your PATH. Add this to ~/.bashrc:"
     echo "      export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac
echo
echo "Tip: set STANDARDS_HOME so any project can install offline:"
echo "      export STANDARDS_HOME=\"$REPO_ROOT\""
echo "Then: cursor-std install /d/path/to/your-project"
echo
echo "Suggested ~/.bashrc entries:"
echo "      export PATH=\"\$HOME/.local/bin:\$PATH\""
echo "      export STANDARDS_HOME=\"$REPO_ROOT\""
